export enum Industry {
  AGRICULTURE = 'AGRICULTURE',
  APPAREL = 'APPAREL',
  BANKING = 'BANKING',
  BIOTECHNOLOGY = 'BIOTECHNOLOGY',
  CHEMICALS = 'CHEMICALS',
  COMMUNICATIONS = 'COMMUNICATIONS',
  CONSTRUCTION = 'CONSTRUCTION',
}
